services:
  scraper:
    build: .
    volumes:
      - ./images:/app/images  # Map the images directory
    environment:
      - DATABASE_URL=postgresql://username:password@db/ecommerce_data
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
